app:
  addr: ':8001'
  api_prefix: '/api/v1'
  debug: true
database:
  username: root
  password: HUST1037!@#$
  host: 'db:3306'
  db_name: ai_recruitment
  charset: utf8
  parse_time: true
  max_idle_conns: 10
  max_open_conns: 30
jwt:
  key: "FUCKINGSoftwareEngine"
  issuer: "HUST"
  expire: 168